#!/bin/csh

# Arg 1: name of branch tag to check out
# Arg 2: Version number to call the whole tar ball

svn export https://svn.mcs.anl.gov/repos/cifts/ftb/trunk -r $argv[1]

mv trunk FTB-$argv[2]

tar czf FTB-$argv[2].tgz FTB-$argv[2]

