/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_NOTIFY_LOGGER_TOTAL_EVENTS 0

FTB_event_info_t ftb_ftb_examples_notify_logger_events[FTB_FTB_EXAMPLES_NOTIFY_LOGGER_TOTAL_EVENTS] = {
};
