/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_PINGPONG_TOTAL_EVENTS 2

FTB_event_info_t ftb_ftb_examples_pingpong_events[FTB_FTB_EXAMPLES_PINGPONG_TOTAL_EVENTS] = {
{"FTB.FTB_EXAMPLES.PINGPONG","PINPONG_EVENT_SRV_CODE", "FTB_INFO", "This event is used by pingpong server"},
{"FTB.FTB_EXAMPLES.PINGPONG","PINPONG_EVENT_CLI_CODE", "FTB_INFO", "This event is used by pingpong client"},
};
