/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_MULTICOMP_COMP2_TOTAL_EVENTS 1

FTB_event_info_t ftb_ftb_examples_multicomp_comp2_events[FTB_FTB_EXAMPLES_MULTICOMP_COMP2_TOTAL_EVENTS] = {
{"FTB.FTB_EXAMPLES.MULTICOMP_COMP2","TEST_EVENT_2_CODE", "FTB_INFO", "Just another test event2"},
};
