/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_MPI_MPI_EXAMPLE_TOTAL_EVENTS 1

FTB_event_info_t ftb_mpi_mpi_example_events[FTB_MPI_MPI_EXAMPLE_TOTAL_EVENTS] = {
{"FTB.MPI.MPI_EXAMPLE","MPI_SIMPLE_EVENT_CODE", "FTB_INFO", "This event is used by a sample mpi application"},
};
