/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_SIMPLE_TOTAL_EVENTS 1

FTB_event_info_t ftb_ftb_examples_simple_events[FTB_FTB_EXAMPLES_SIMPLE_TOTAL_EVENTS] = {
{"FTB.FTB_EXAMPLES.SIMPLE","SIMPLE_EVENT_CODE", "FTB_INFO", "This event is used for testing and examples"},
};
