/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_MULTICOMP_COMP3_TOTAL_EVENTS 1

FTB_event_info_t ftb_ftb_examples_multicomp_comp3_events[FTB_FTB_EXAMPLES_MULTICOMP_COMP3_TOTAL_EVENTS] = {
{"FTB.FTB_EXAMPLES.MULTICOMP_COMP3","TEST_EVENT_3_CODE", "FTB_INFO", "Just another test event3"},
};
