/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_MPI_MPICH_TOTAL_EVENTS 2

FTB_event_info_t ftb_mpi_mpich_events[FTB_MPI_MPICH_TOTAL_EVENTS] = {
{"FTB.MPI.MPICH","MPI_OUT_OF_RESOURCES_CODE", "FTB_ERROR", "MPI is out of resources"},
{"FTB.MPI.MPICH","MEM_REGISTER_FAIL_CODE", "FTB_FATAL", "Memory Registration failed"},
};
