/* This file is automatically generated */

#include "ftb_def.h"

#define FTB_FTB_EXAMPLES_WATCHDOG_TOTAL_EVENTS 1

FTB_event_info_t ftb_ftb_examples_watchdog_events[FTB_FTB_EXAMPLES_WATCHDOG_TOTAL_EVENTS] = {
{"FTB.FTB_EXAMPLES.WATCHDOG","WATCH_DOG_EVENT_CODE", "FTB_INFO", "This event is used by watchdog"},
};
